### ISSUE TITLE
Binary naming issue 

### ISSUE THREAD

**Issue by DimensionalDrift** [zxqfl/tabnine-sublime#47]
Hey @zxqfl, the latest commit seems to have broken TabNine for me. I am getting errors in the sublime console such as: 

> Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 627, in on_activated_async
    callback.on_activated_async(v)
  File "/home/chris/.config/sublime-text-3/Packages/TabNine/TabNine.py", line 237, in on_activated_async
    tabnine_proc.request(request)
  File "/home/chris/.config/sublime-text-3/Packages/TabNine/TabNine.py", line 89, in request
    self.restart_tabnine_proc()
  File "/home/chris/.config/sublime-text-3/Packages/TabNine/TabNine.py", line 85, in restart_tabnine_proc
    startupinfo=get_startup_info(sublime.platform()))
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1370, in _execute_child
  File "./python3.3/os.py", line 791, in fsencode
TypeError: expect bytes or str, not NoneType

After a bit of digging I have traced the issue back to the updated binaries, either you have forgotten to rename them from `x86_64-unknown-linux-gnu` to `x86_64-unknown-linux-musl` or you have forgotten to change the names of the binaries [here](https://github.com/zxqfl/tabnine-sublime/blob/ea8244ef87930d6f52c07cc3fc42ad25ad43a7ca/TabNine.py#L32). Renaming the binaries found in  `~/.config/sublime-text-3/Packages/TabNine/binaries/2.1.22` helped me (linux Ubuntu), hope this helps anyone else having issues!

**Comment by zxqfl** [comment]
Thank you!
